apiVersion: v1
clusters:
- cluster:
    certificate-authority: C:\Users\deadm\.minikube\ca.crt
    extensions:
    - extension:
        last-update: Wed, 10 Jul 2024 13:33:58 MSK
        provider: minikube.sigs.k8s.io
        version: v1.33.1
      name: cluster_info
    server: https://172.26.37.234:8443
  name: minikube
contexts:
- context:
    cluster: minikube
    extensions:
    - extension:
        last-update: Wed, 10 Jul 2024 13:33:58 MSK
        provider: minikube.sigs.k8s.io
        version: v1.33.1
      name: context_info
    namespace: default
    user: minikube
  name: minikube
current-context: minikube
kind: Config
preferences: {}
users:
- name: minikube
  user:
    client-certificate: C:\Users\deadm\.minikube\profiles\minikube\client.crt
    client-key: C:\Users\deadm\.minikube\profiles\minikube\client.key
